language: node_js

node_js:
- 'node'

services:
- docker

os:
- linux
dist: trusty # using Ubuntu 14.04.5 LTS

branches:
  only:
  - master
  - develop
  - /v?[0-9]+\.[0-9]+\.[0-9]+(.*)?/

env:
  global:
    - ISPRODTAG=^v?[0-9]+\.[0-9]+\.[0-9]+$
    - ISTESTTAG=^v?[0-9]+\.[0-9]+\.[0-9]+-[rR][cC]
    - RC_EXTENSION_ID="iotdevexbuild.test-owl-project"

install:
- sudo apt-get install libsecret-1-dev
- npm install -g vsce
- npm install

script:
- tsc --version
- gts --version
- gts check
- node scripts/modifyConfigIfRCVersion.js
- node scripts/updateResourceLink.js
- node scripts/genAiKey.js
- node scripts/nightlyBuild.js
- vsce package
- docker run -ti --rm -v $PWD:/mnt:ro dkhamsing/awesome_bot --allow-dupe --allow-redirect --skip-save-results `ls *.md`

before_deploy:
  # Set up git user name and tag this commit
  - git config --local user.name "YOUR GIT USER NAME"
  - git config --local user.email "YOUR GIT USER EMAIL"
  - export TRAVIS_TAG=${TRAVIS_TAG:-$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)}
  - git tag $TRAVIS_TAG

deploy:
  # deploy to github release
  - provider: releases
    api_key: $GIT_TOKEN
    file_glob: true
    file: "*.vsix"
    skip_cleanup: true
    on:
      tags: true
      all_branches: true
      condition: $TRAVIS_TAG =~ $ISPRODTAG OR $TRAVIS_TAG =~ $ISTESTTAG
  # deploy to vscode extension market
  - provider: script  
    script: vsce publish -p $VSCE_TOKEN --packagePath *.vsix
    skip_cleanup: true
    on:
      tags: true
      all_branches: true
      # if it's a PROD tag (something like 1.0.0), then publish extension to market.
      condition: $TRAVIS_TAG =~ $ISPRODTAG
  # deploy test version to vscode extension market
  - provider: script
    script: yes | vsce unpublish -p $VSCE_TEST_TOKEN $RC_EXTENSION_ID && vsce publish -p $VSCE_TEST_TOKEN --packagePath *.vsix
    skip_cleanup: true
    on:
      tags: true
      all_branches: true
      # if it's a test version tag (something like 1.0.0-rc), then publish test extension to market.
      condition: $TRAVIS_TAG =~ $ISTESTTAG
  # deploy nightly build to github release
  - provider: releases
    api_key: $GIT_TOKEN
    overwrite: true
    file_glob: true
    file: "*.vsix"
    skip_cleanup: true
    on:
      all_branches: develop
      condition: $TRAVIS_EVENT_TYPE = "cron"