trigger:
  branches:
    include:
    - master
    - develop

jobs:
- job: Windows

  pool:
    name: Hosted VS2017
    demands: npm

  steps:
  - task: Npm@1
    displayName: 'Install dependencies'
    inputs:
      verbose: false
  - task: Npm@1
    displayName: 'Compile sources'
    inputs:
      command: custom
      verbose: false
      customCommand: 'run compile'
  - script: npm install -g vsce
    displayName: 'install vsce'
  - script: gts check
    displayName: 'check gts error'
    failOnStderr: True
  - script: node scripts/updateConfigIfProduction.js
    displayName: 'Update configuration for production'
  - script: vsce package
    displayName: 'Build VSIX package'
  - task: CopyFiles@2
    inputs:
      SourceFolder: '$(System.DefaultWorkingDirectory)'
      Contents: |
        **\*.vsix
      TargetFolder: '$(Build.ArtifactStagingDirectory)'
  - task: PublishBuildArtifacts@1
    inputs:
      pathtoPublish: '$(Build.ArtifactStagingDirectory)'  
      artifactName: workbench-windows-drop

- job: macOS
  pool:
    name: Hosted macOS
    demands: npm
  steps:
  - task: UseNode@1
    displayName: 'Install node version >=12.0.0'
    inputs:
      version: '>=12.0.0'
  - task: Npm@1
    displayName: 'Install dependencies'
    inputs:
      verbose: false
  - task: Npm@1
    displayName: 'Compile sources'
    inputs:
      command: custom
      verbose: false
      customCommand: 'run compile'
  - script: sudo npm install -g vsce
    displayName: 'install vsce'
  - script: node node_modules/gts/build/src/cli.js check
    displayName: 'check gts error'
    failOnStderr: True
  - script: node scripts/updateConfigIfProduction.js
    displayName: 'Update configuration for production'
  - script: vsce package
    displayName: 'Build VSIX package'
  - task: CopyFiles@2
    inputs:
      SourceFolder: '$(System.DefaultWorkingDirectory)'
      Contents: |
        **/*.vsix
      TargetFolder: '$(Build.ArtifactStagingDirectory)'
  - task: PublishBuildArtifacts@1
    inputs:
      pathtoPublish: '$(Build.ArtifactStagingDirectory)'  
      artifactName: workbench-macos-drop

- job: Linux

  pool:
    name: Hosted Ubuntu 1604
    demands: npm

  steps:
  - task: Npm@1
    displayName: 'Install dependencies'
    inputs:
      verbose: false
  - task: Npm@1
    displayName: 'Compile sources'
    inputs:
      command: custom
      verbose: false
      customCommand: 'run compile'
  - script: sudo npm install -g vsce
    displayName: 'install vsce'
  - script: node node_modules/gts/build/src/cli.js check
    displayName: 'check gts error'
    failOnStderr: True
  - script: node scripts/updateConfigIfProduction.js
    displayName: 'Update configuration for production'
  - script: vsce package
    displayName: 'Build VSIX package'
  - task: CopyFiles@2
    inputs:
      SourceFolder: '$(System.DefaultWorkingDirectory)'
      Contents: |
        **/*.vsix
      TargetFolder: '$(Build.ArtifactStagingDirectory)'
  - task: PublishBuildArtifacts@1
    inputs:
      pathtoPublish: '$(Build.ArtifactStagingDirectory)'
      artifactName: workbench-ubuntu-1604-drop
  # Deploy to Github Release
  - task: GitHubRelease@1
    inputs:
      gitHubConnection: 'dilin-ms-test'
      repositoryName: '$(Build.Repository.Name)'
      action: 'create'
      target: '$(Build.SourceVersion)'
      tagSource: 'gitTag'
      changeLogCompareToRelease: 'lastFullRelease'
      changeLogType: 'commitBased'
  # Deploy to production marketplace
  - bash: vsce publish -p $MARKETPLACE_TOKEN --packagePath *.vsix
    workingDirectory: '$(Build.ArtifactStagingDirectory)/workbench-ubuntu-1604-drop'
    displayName: 'Deploy to production marketplace'
    env:
      MARKETPLACE_TOKEN: $(dilin_marketplace_token)